### ISSUE TITLE
Spelling issue (setup vs set up)

### ISSUE THREAD

**Issue by KristinaMayman** [gnosis/safe-browser-extension#101]
## Description

On the screen that appears after the password is created and confirmed, a message below the header says "Extension setup succesfully!". "Setup" is spelled as one word when it is a noun or an adjective but separately when it is a verb. Thus, the message should be either "Extension set up successfully!" or "Extension setup successful!". 

## Environment

Safe browser extension version: 1.2.1
Browser version: 71.0.3578.98 (Official Build) (64-bit)
Operating system: Windows 10 Home

## Steps to reproduce

1. Complete the steps to create a password.
2. Confirm the password.
3. Click on Next.

## Additional context

Dictionary:
https://www.merriam-webster.com/dictionary/setup
Rule explanation:
https://grammarist.com/spelling/set-up-vs-setup/

**Comment by rmeissner** [comment]
I would argue that this is correct. See http://www.future-perfect.co.uk/grammar-tip/is-it-setup-set-up-or-set-up/

**Comment by KristinaMayman** [comment]
I think the article you sent just notes that in the IT context, the hyphen is omitted in the nouns and adjectives. But in the extension the word is written together, even though it is a verb.
