### ISSUE TITLE
The QR code to connect a new safe is uncompletely shown

### ISSUE THREAD

**Issue by MicaelaPesado** [gnosis/safe-browser-extension#139]
#Testing the new staging version#

## Description
When trying to connect an address, it is imposible because the QR code displayed is shown wrongly.

![image](https://user-images.githubusercontent.com/44403034/63032491-4d1dac80-be8c-11e9-8898-c5eae3297b83.png)

## Enviorment:
Rebranding release (v1.5.0)

**Comment by germartinez** [comment]
That's related with the language.
I will check all of them and not just english.
Thanks @MicaelaPesado
