### ISSUE TITLE
Unable to approve transactions via extension | Chrome

### ISSUE THREAD

**Issue by RyRy79261** [gnosis/safe-browser-extension#145]
## Description
I was attempting to upgrade my safe for the security notice, once on the review transaction screen of my S10 android app, it sent a confirmation request to the safe extension in my chrome browser on windows 10, after hitting confirm, entering my password, nothing happens, the reject, confirm buttons disappear and upon inspection of the pop up, theres an error: `POST https://safe-notification.gnosis.pm/api/v1/notifications/ net::ERR_ABORTED 404` 

## Environment

- Authenticator version: 1.8.1 
- Browser version: Extension: 1.5.0 on Chrome Version 77.0.3865.120 (Official Build) (64-bit)
- Operating system: Windows 10 & Android 9

## Steps to reproduce

* Open andoid app.
* Click security upgrade notice at top
* Hit next till review transaction screen

* Desktop notification pops up from browser
* Click confirm
* Enter password

![image](https://user-images.githubusercontent.com/10461622/66829243-44605a00-ef53-11e9-83f2-79c12204902c.png)

**Comment by rmeissner** [comment]
Hey, thanks for the issue report. Could you possibly send the response from the service (it should include an error message)? Normally a 404 indicates that our backend doesn't know the devices that you try to notify. 

Some additional questions:
Did you confirm a transaction before? What Android device are you using?

**Comment by RyRy79261** [comment]
Hi @rmeissner 

I have used the extension with this safe previously, I'm using a Samsung S10. 

I can send the response in the morning but I am attempting to do the security upgrade notice that I'm now seeing in the app

**Comment by RyRy79261** [comment]
@rmeissner 

So for context the tx is being initiated from my phone, and trying to repeat this morning the notification doesn't even display on the authenticator

**Comment by rmeissner** [comment]
hey,
for not seeing the confirmation request in the extension, can you try to press "resync" option in the extension menu?

**Comment by RyRy79261** [comment]
The request payload has devices, a stringified message json & signature 


![image](https://user-images.githubusercontent.com/10461622/66900500-3535e680-effd-11e9-9d4c-10408d0aaf54.png)

**Comment by RyRy79261** [comment]
I tried sending it through postman manually and just got an empty response

**Comment by rmeissner** [comment]
Hey, thanks for the details I will try to look into it.

**Comment by rmeissner** [comment]
Do you by any chance have telegram, if so could you find me in the Gnosis Safe group (https://t.me/GnosisSafe) so that we could exchange more information?

**Comment by rmeissner** [comment]
After some debugging we found out that the extension uses a wrong key, therefore it cannot send a push since there is not authorized pair. It is unknown why the extension is in a wrong state.

The address of the secondFA stored in local storage is not an owner of the Safe, but it has never been replaced.

**Comment by rmeissner** [comment]
This inconsistent state of the extension happened after a recovery of a Safe

**Comment by RyRy79261** [comment]
Both the app and the extension share the same address, and transaction approval requests from my device pop up on the extension.

When trying to change the recovery phrase, the device says the extension is not connected to the current safe

**Comment by RyRy79261** [comment]
@germartinez I attempted to use my account again and theres been no change to the errors.

**Comment by rmeissner** [comment]
Hey, the fix will be included in the next update

**Comment by germartinez** [comment]
Hello @RyRy79261 ,

If you want to find more information about this issue please take a look at the Github issue included in the next release (v1.5.2) here: https://github.com/gnosis/safe-browser-extension/issues/148. It will be in the next one because there is some work needed in the mobile apps side too.

If you are using the Gnosis Safe Authenticator from the Chome Store, notice that it was not updated to v1.5.1 yet. To solve your issue, right now you would need to uninstall your Safe Authenticator and install it again.

Sorry for the inconvenince.

**Comment by germartinez** [comment]
If you are running the Authenticator locally with the version 1.5.1, you could follow these steps:
- Display the qr-code to add a ne wSafe in the Authenticator
- In your Safe mobile app, replace the current Authenticator by scanning the qr-code
- In your Safe mobile app, click on "Resync with Authenticator" (this point will be unnecesary after v1.5.2)

**Comment by RyRy79261** [comment]
@germartinez  Ok cool thank you, 

We ran into a couple conflicts on with trying to set up a new authenticator when we were looking into the issue last time so I'll wait for the next update
