### ISSUE TITLE
Add web3 constructor

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe-browser-extension#42]
Naming the Web3 constructor something like `Gnosis Safe` so I can do `web3.constructor.name` to check the provider.

Also it would be nice to have a `isGnosisSafe` function on the provider that returns `true` for the one injected by the Safe extension

**Comment by W3stside** [comment]
:+1: yeah yo

**Comment by germartinez** [comment]
@rmeissner @W3stside 
The [safe-web3-provider](https://github.com/gnosis/safe-web3-provider) was updated and calling to `web3.currentProvider.constructor.name` now returns `SafeWeb3Provider`.

Here is an example from our example dapp using the safe-web3-provider: https://github.com/gnosis/example-safe-web3-provider/blob/72f280ee554168a59d95ead27b03d3e819683cb4/src/components/Page/index.js#L47

If a dapp integrates with the safe-web3-provider directly, this is now available, in other case the extension will use the updated provider in the next release.
