### ISSUE TITLE
Improve unlock behaviour

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe-browser-extension#43]
1. `Unlock` button in extension when signing tx first time is hidden, didnt know where to look, maybe point an arrow at it?
2. When hitting the `unlock` button (as above) can you guys auto-focus in the field? I kept typing my password elsewhere

**Comment by W3stside** [comment]
whoever's coming up with these is a beast

**Comment by germartinez** [comment]
Done.
Will be included in the next release.
Thank you!
