### ISSUE TITLE
Sending a confirm push notification fails

### ISSUE THREAD

**Issue by fmrsabino** [gnosis/safe-browser-extension#44]
Tested on commit: `84b0f0cc2a7e791d1fc84d3dcb21a266f02f4223`

When I press the `Confirm` button to send a push notification the buttons just disappear.
The console shows the following error message:

```
POST https://safe-notification.staging.gnosisdev.com/api/v1/notifications/ 403 (Forbidden)
```

With the following response:
```
{"detail":"CSRF Failed: Referer checking failed - no Referer."}
```

**Comment by fmrsabino** [comment]
This is in the `Request Headers`:
```
Cookie: csrftoken=zzGkuZDs2oGACItWFsTv5X4Qh5jB60pNprmvVmZqqio8pnkpjys6fffitIlsMPbU; sessionid=yhc1muou3bg7rc9yotagksrlb4c34456
```

**Comment by giacomolicari** [comment]
I had a look at the backend service, the issue could be related with the following settings:
https://docs.djangoproject.com/en/dev/ref/settings/#session-cookie-httponly
https://docs.djangoproject.com/en/dev/ref/settings/#csrf-cookie-httponly

but needs some more digging.

Is the app able to get the CSRF token and the session cookie?

**Comment by rmeissner** [comment]
On Android we are not using any cookies, therefore we don'T have this issue.

**Comment by giacomolicari** [comment]
Ok, I was referring to the browser-extension in this case. I will also disable CSRF on the transaction-history :)
