### ISSUE TITLE
Error when executing multiple transactions

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-browser-extension#65]
Reopening this issue here, moved over from gnosis/safe-android#245 (check discussion there as well)

**Describe the bug**
When I use https://rinkeby.slow.trade, I have to sign multiple txs. I get an error the first time I try to do tx no 2 and 3

**To Reproduce**
1. I have a Safe installed an a Chrome extension connected
2. Go to https://rinkeby.slow.trade
3. Trade something
4. Confirm tx1
5. Trigger tx no2 (the one where you approve)
6. I get the push on the phone
7. I tap "Confirm"
8. I use fingerprint to submit
💥 An error occurred. (Also on retrying multiple times)
9. I close the tx.
10. I resend the push from the extension
11. Now I can submit successfully.

**Expected behavior**
No error

**Screencast**
https://drive.google.com/file/d/1mXF6XN_Zyf1U5Dlj77JB9A8Wu8NWVaew/view?usp=sharing

**Smartphone (please complete the following information):**
 - Device: Gnosis MotoG
 - Android Version: 7.1.1
 - App Version: 0.6.3-8-g7e...internal

- Chrome extension version: 0.4.0 (internal/red)

**Additional context**
-

**Comment by fmrsabino** [comment]
Described the issue in more detail here @germartinez 
https://github.com/gnosis/safe-android/issues/245#issuecomment-428990898
