### ISSUE TITLE
Expose `eth_coinbase` and `eth_accounts` via `sendSync`

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe-browser-extension#75]
## Context / issue

Gitcoin requires that `eth_coinbase` and `eth_accounts` can be queried synchronously. Currently we only allow this asynchronously.

## Proposed solution

Add handling for these methods to the `SafeProvider::sendSync` method

## Additional context

To test if this is working open https://gitcoin.co/funding/new and try to trigger a transaction.

**Comment by germartinez** [comment]
Implemented here: https://github.com/gnosis/safe-browser-extension/pull/93
