### ISSUE TITLE
QR Code not showing in Chrome

### ISSUE THREAD

**Issue by aliblackwell** [gnosis/safe-browser-extension#83]
## Description

I've installed both the Rinkeby beta browser extension and the production browser extension. It lets me create a password and the QR code to download the Android app loads as expected. But when I click 2) Show QR Code a blank white box with the "BROWSER EXTENSION" title appears – no QR code.

## Environment

- Both Rinkeby and Production versions, installed ~20 mins before this issue was filed
- Chrome Version 70.0.3538.102
- Mac OS Mojave 10.14

**Comment by germartinez** [comment]
Hello @aliblackwell,
This is something I cannot reproduce.
- Did you have internet connection at that time (there is a request made before showing the qr-code)
- Does still happening if you download the extension and try again?
- Could you check that the service worker "firebase-messaging-sw.js" is running after clicking on the button to show the qr-code? (Inspect the extension -> Application tab -> Service workers)
- If the qr-code does not appear, could you follow these steps? inspect the extension -> Network tab -> click on the "show qr-code" button (do this now, not before inspecting) -> check the request to "/auth" -> paste here the content in the Response tab
Thank you

**Comment by aliblackwell** [comment]
Hey @germartinez apologies for delay getting back to you, I missed this notification. I have just tried it and it's working. It must've been my internet connection in that case. But then I was able to post this issue and I did re-check it whilst drafting the issue. I'd suggest adding some error-handling for when the network drops out, or something to verify the QR code has rendered and if it hasn't, display a message asking the user to check their connection.

**Comment by tasdienes** [comment]
I am having the same issue, but I am using Brave (Version 0.62.51 Chromium: 73.0.3683.103 (Official Build) (64-bit) Windows).  I'm using Safe Mainnet Beta 1.3.4.  I've reproduced the problem several times over the last ~week (it never displays the QR code).

Following the troubleshooting steps above:

>Could you check that the service worker "firebase-messaging-sw.js" is running after clicking on the button to show the qr-code? (Inspect the extension -> Application tab -> Service workers)
Status is "activated and stopped"

If the qr-code does not appear, could you follow these steps? inspect the extension -> Network tab -> click on the "show qr-code" button (do this now, not before inspecting) -> check the request to "/auth" -> paste here the content in the Response tab
I'm not seeing a request to /auth when I click on the "Show QR Code" button.

**Comment by germartinez** [comment]
Hello @tasdienes,

Please check this message:
https://github.com/gnosis/safe-browser-extension/issues/80#issuecomment-478531354
