### ISSUE TITLE
Cannot confirm / reject when there are multiple confirmation requests

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-browser-extension#89]
## Description
I try to transfer tokens with my iOS Safe app, but first entered the wrong amount. Now I cannot reject or continue anymore. (See video)

## Environment
Mainnet
- Safe browser extension version: Version: 1.0.0
- Browser version: Let me know if this is important
- Operating system: MacOS
- I used the iOS app v 0.10.0 on my iPhone SE

## Steps to reproduce
* Initiate transfer of DAI from iOS app
* I first entered the full amount available
* Hit next, i.e. Chrome extension is asked for confirmation
* Ignore Chrome popup, don't click anything.
* Now in iOS app, go back
* Enter a lower amount
* Hit next, so Chrome gets another push
* Now try to reject or confirm
-> Doesn't work (see video)
 
## Additional context

Screencast: https://drive.google.com/open?id=1mqqM0Re42xUaaipPKSfYWkkYFYeo5SzQ

**Comment by tschubotz** [comment]
I just realized that apparently, the confirmation was still sent to the app. i.e. I could submit the tx without further ado. Just the UI in the extension didn't update apparently. Let me know if you need more details.

**Comment by germartinez** [comment]
Thank you @tschubotz
